### ISSUE TITLE
Issue with testing annual data

### ISSUE THREAD

**Issue by rabutler-usbr** [BoulderCodeHub/RWcheck#5]
When testing an annual series slot, the test is coming back as having passed 961 and failing 10571. 

The output includes 31 traces of 31 years (961 total years). So - the tests are passing for December of every year, but failing for January - November each year. 

If you read the rdf directly, it does indeed include only annual data, i.e., it does not have NaNs for Jan-Nov. This indicates something in the process is adding a bunch of data or somehow not respecting/realizing it is annual data. 

See the code and yaml file in #4 to recreate the issue.

**Comment by sbaker2423** [comment]
This is happening from a spread() in read_scenarios()... This format is necessary for the current why validate::confront() is used. Need to add a loop through rules and select only necessary slots so NaNs arent created...
