### ISSUE TITLE
Need some way to filter by user specified month

### ISSUE THREAD

**Issue by rabutler-usbr** [BoulderCodeHub/RWcheck#6]
Some annual slots are expected to be filled with NaN for January - November, ex: `PowellOperation.PowellWYRelease[]`. 

Currently if you check !is.na(PowellOperation.PowellWYRelease), the test will fail for January - November, but pass in December. 

Since we expect it to be NaN in Jan-Nov, we should be able to specify that the test should only be performed in December. 

Perhaps this could be an optional "month" entry in the yaml file?

**Comment by sbaker2423** [comment]
This seems like a good enhancement. I will add an optional input to the yaml file to input months.
